import { Users } from '../../src/resources/users/entities/users.entity';
import { UserProbation } from '../../src/common/entities/UserProbation';

export const mockUser: Users = {
    address: '',
    avatar: '',
    birthDay: null,
    chiefId: 0,
    company: '',
    companyId: 4,
    country: '',
    daysOff: [],
    emailSpare: '',
    eventsByUsers: [],
    eventsByUsersRequest: [],
    firstDayInCompany: null,
    firstName: '',
    googleCalendars: {
        id: 1,
        userId: 1,
        calendarId: '1',
        timezone: 1,
        user: {} as Users
    },
    isActive: 0,
    jobPosition: '',
    jobPositionDetails: [],
    lastDayInCompany: null,
    lastLogin: null,
    lastName: '',
    loginCount: 0,
    mentorId: 0,
    password: '',
    phone: '',
    role: 'user',
    skype: '',
    taskProjectPermissions: [],
    tokenActivation: '',
    tokenReset: '',
    userChiefRelations: [],
    userChiefRelationsByChief: [],
    userProbation: {} as UserProbation,
    userRelationToGroups: [],
    id: 1,
    email: 'test@gmail.com' };
