import { Users } from '../../src/resources/users/entities/users.entity';

export const mockUser: Users = {
    address: '',
    avatar: '',
    birthDay: undefined,
    chiefId: 0,
    company: '',
    companyId: 0,
    country: '',
    daysOff: [],
    emailSpare: '',
    eventsByUsers: [],
    eventsByUsersRequest: [],
    firstDayInCompany: undefined,
    firstName: '',
    googleCalendars: undefined,
    isActive: 0,
    jobPosition: '',
    jobPositionDetails: [],
    lastDayInCompany: undefined,
    lastLogin: undefined,
    lastName: '',
    loginCount: 0,
    mentorId: 0,
    password: '',
    phone: '',
    role: undefined,
    skype: '',
    taskProjectPermissions: [],
    tokenActivation: '',
    tokenReset: '',
    userChiefRelations: [],
    userChiefRelationsByChief: [],
    userProbation: undefined,
    userRelationToGroups: [],
    id: 1,
    email: 'test@gmail.com' };
